### PR TITLE
WIP Refactor to use the Cobra CLI

### PR DESCRIPTION
**Pull request by bbriggs**
_Massive_ refactor and I'll rebase back. Submitting for early review and to get feedback on "directional accuracy."

The idea is that, like the issue originally stated, each top level command would get its own directory. This is further required by the fact that many of the subcommands each in turn has (or will have) its own subcommands that share a name.

To do this with Cobra, we treat each top level subcommand as its own app, import them in the new `cmd` directory, and call them from there.

Examples of this plan in action:

```
go run ./main.go --help
A brief description of your application

Usage:
  hassio [flags]
  hassio [command]

Available Commands:
  addons        
  hardware      A brief description of your command
  hassos        A brief description of your command
  help          Help about any command
  homeassistant A brief description of your command
  host          A brief description of your command
  snapshots     A brief description of your command
  supervisor    A brief description of your command

Flags:
      --config string   config file (default is $HOME/.homeassistant.yaml)
  -h, --help            help for hassio
```

```
go run ./main.go addons
addons sub-command
```

And of course, our aliases work.
```
go run ./main.go ad
addons sub-command
```

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @bbriggs, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-cli#117).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
This is an empty shell, which is fine at this stage but let's not merge it into `dev` to prevent us losing control of the current code base (in case of hotfixes or needed changes).

Maybe create the PR against the `2.0.0` branch?

**Comment by bbriggs** [comment]
New base branch targeted

**Comment by bbriggs** [comment]
So just to confirm, the current design is what we're looking for? We can proceed with this pattern?

**Comment by frenck** [comment]
I think the general pattern is OK, I'm currently looking for a way on how to move this forward. I'll get back to this PR... sorry to keep you waiting.

**Comment by bbriggs** [comment]
In order to make passing global options/arguments/flags easier, I opted to go for a single directory and package instead. It makes for more files that have to be named uniquely and more contention for variable names, but ultimately a simpler configuration.

**Comment by mjrider** [comment]
hello @bbriggs thx for the continuation if this PR, could you target the next branch for this, This because the amount of rewrites required for different PR's and to prevent to many merge conflicts between those rewrites. I already fixed the setup of logging and command line / env keys / configfile handling in that branch

**Comment by bbriggs** [comment]
Sure. What's the branch to target?

**Comment by mjrider** [comment]
The name of the branch is _next_. This is your previous PR with the fixes in the development and continued development on your PR

**Comment by frenck** [comment]
Updated target to `next`.

**Comment by mjrider** [comment]
> @mjrider This has already been manual merged into the `next` branch so it seems?
i have to check, but i guess he force pushed at some point in time, which creates conflicts because i already pulled his previous branch in next

**Comment by frenck** [comment]
Check, @bbriggs, it is in the `next` branch.
So I'm closing this PR.

**Pull request closed without merging**
