### PR TITLE
Use goimports

### PR DESCRIPTION
**Pull request by moorereason**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @moorereason, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-cli#65).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by moorereason** [comment]
This PR uses [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) to gofmt and sort import paths.

**Comment by pvizeli** [comment]
please only change lines that are affect to the context of PR and not every line. Follow also our code guide i.e. 4 space idents.

**Comment by moorereason** [comment]
I assume you are referring to https://home-assistant.io/developers/development_guidelines/.  If so, I totally agree, but those guidelines are for Python.

I don't mean to offend, but I do want to be candid.  Go is different and has its own style.  I would highly recommend using gofmt (or goimports) with Go source instead of using your preferences for Python.  As Robert Griesemer says in his presentation entitled __[The Cultural Evolution of gofmt](https://talks.golang.org/2015/gofmt-en.slide)__, gofmt "defines *de facto* Go formatting."  There are no style guides in the Go community.  It's assumed that everyone is using gofmt.

This PR simply runs goimports against the codebase (`goimports -w .`).  I made no other changes.  There's real changes I'd like to make, but I wanted to fix the gofmt issue first.

On a side note, many Go projects put a Go Reportcard badge in their README.  bassio-cli currently has a [B grade](https://goreportcard.com/report/github.com/home-assistant/hassio-cli) because gofmt isn't being used.

**Comment by pvizeli** [comment]
4 space and 80 character lines are the minimum of language indipendent style.

**Pull request merged**
